version: '2.0'
services:
    php-fpm:
        image: coincan/php:7.2-2
        container_name: pi-cans-phpfpm
        restart: on-failure
        volumes:
          - ./html:/var/www/html:rw
          - ./provision/php-fpm:/etc/php7/php-fpm.d:ro
        environment:
          - PUID="1000"
          - PGID="1000"
          - TZ="Australia/Melbourne"
        expose:
          - 9720

    nginx:
        image: coincan/nginx:1.14
        depends_on:
          - php-fpm
        links:
          - php-fpm
        container_name: pi-cans-nginx
        volumes:
          - ./html:/var/www/html:rw
          - ./provision/nginx/site.nginx.conf:/etc/nginx/conf.d/default.conf:ro
          - ./:/run/nginx
        restart: on-failure
        ports:
          - "80:80"
          - "443:443"
